12C New Features:
			  1. Top N queries using FETCH FIRST and OFFSET
			  2. Extended String Datatypes
              3. Multiple indexes on the same column
			  4. Handling default columns in Oracle 12c
			  5. Identity Columns
			  
1. Top N queries using FETCH FIRST and OFFSET
               SELECT employee_id, last_name
                 FROM employees
                 ORDER BY salary
                 FETCH FIRST 5 ROWS ONLY;
            	--FETCH FIRST 5 PERCENT ROWS WITH TIES;
                --OFFSET 4 ROWS FETCH NEXT 4 ROWS ONLY

2. Extended String Datatypes
            ALTER SYSTEM SET max_string_size='EXTENDED';   4000 -> 32767
			ALTER SESSION SET nls_date_format='D/MM/YYYY'

3. Multiple indexes on the same column
             In order to test the invisible indexes, you need to set the optimizer_use_use_invisible_indexes=true.
			 
			  CREATE INDEX emp_ind1 ON EMP(ENO,ENAME);
			  CREATE BITMAP INDEX emp_ind2 ON EMP(ENO,ENAME) INVISIBLE;      --Index type should be different
		
4. Handling default columns in Oracle 12c
            CREATE TABLE sample(id VARCHAR2(100) DEFAULT ON NULL 13
			                    id2 NUMBER DEFAULT s.NEXTVAL PRIMARY KEY)      
         						  
5. Identity Columns			  
			  SQL> create table t_id_col ( x number generated by default as identity(start with 10 increment by 15 ) primary key,
                                          y varchar2(30))
/
          
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  
		  